### ISSUE TITLE
Can't view notes on Android

### ISSUE THREAD

**Issue by Rom1-GoPlay** [omnivore-app/omnivore#2078]
When I take a note on an article with the android application. If I close the article and open it again, I can't see the note (I can only edit a new one).

**Comment by jacksonh** [comment]
@Rom1-GoPlay thank you, this is useful. We will work on fixing this.

**Comment by Rom1-GoPlay** [comment]
I am glad to have helped !
Thank you for your work !

**Comment by Tryphan** [comment]
The same issue is seen with highlighting as well, not just notes.

**Comment by jacksonh** [comment]
Hello, I haven't been able to replicate this. Are you saying if you add a highlight on Android it is not visible?

**Comment by Tryphan** [comment]
That is correct. I've only just started using the app and highlighted 3 
articles. When I went back to continue, none of my previous highlights 
were there.

**Comment by thiswillbeyourgithub** [comment]
Confirmed here. My highlights seem to appear on firefox android but not on the android app. It's quite scary and i think it's why i stayed away from omnivore a few months ago to let it mature (could be mistaken)

**Comment by Rom1-GoPlay** [comment]
> When I take a note on an article with the android application. If I close the article and open it again, I can't see the note (I can only edit a new one).

Now it is different: when I open the article again (with the android application) I can't even view where there is a note. And yes, highlights also are invisible now. I am using the version 0.0.32 of the application.
Unfortunately, I don't remember which version I was using when I opened the issue.

**Comment by Rom1-GoPlay** [comment]
When I open an article with the web version I can see everything I have highlighted on android even notes. But android can't. When I highlight or note somthing on the web version, I can't see it with android.
So I think that the android application open articles without highlight and notes. I believe the bug occur when the  android app open an article (not when it saves it).

**Comment by jacksonh** [comment]
thank you, i am hoping this is fixed in `0.44` which is in review now.

**Comment by jacksonh** [comment]
@Rom1-GoPlay can you check now? I am unable to replicate this issue with 0.4 build

**Comment by Rom1-GoPlay** [comment]
I am now using 0.0.44 and when I open an article, I can't see highlights or notes.
Sorry, the bug remain.

**Comment by jacksonh** [comment]
Thank you, actually I just found it and am uploading a new build.

**Comment by thiswillbeyourgithub** [comment]
Works fine for me. Thanks a lot!

**Comment by Tryphan** [comment]
My initial use of the latest release seems to have fixed the highlighting issue for me too. Great work! Thanks!

**Comment by Rom1-GoPlay** [comment]
I am on Github since only one week and I don't know if I have to do somthing now... Maybe I should close the issue but I don't know how.

**Comment by jacksonh** [comment]
I will close this one now as we just added a readonly version of Notebooks, so you can see all your highlights and notes in the Notebook. Next step is allowing to create/edit notes on Android.
