### ISSUE TITLE
Autocompletion suggestions in extension make labeling difficult

### ISSUE THREAD

**Issue by xplosionmind** [omnivore-app/omnivore#2214]
As the image below shows, when assigning tags to an article saved via extension (on Firefox), autocompletion suggestions cover some labels. Autocompletion suggestions should not be appearing…

![Screenshot from 2023-05-18 09-45-34](https://github.com/omnivore-app/omnivore/assets/42862428/00e454de-c47b-4f8a-a77b-25b4672db5d5)

**Comment by jacksonh** [comment]
Thanks!

**Comment by jacksonh** [comment]
Looks like i just need to add `autocomplete="off" `

**Comment by jacksonh** [comment]
ok hoping to get an update out for Firefox today with this one. Chrome maybe monday

**Comment by jacksonh** [comment]
Fixed!

**Comment by xplosionmind** [comment]
I am sorry to report that the issue is not fixed, yet… Running Omnivore extension version 2.2.1 on Firefox 115.0

**Comment by xplosionmind** [comment]
Pinging again @jacksonh, the issue is still there… Omnivore extension version 2.6.2 on Firefox 119.0:

<img width="476" alt="Screenshot 2023-11-05 at 10 18 44" src="https://github.com/omnivore-app/omnivore/assets/42862428/67e4f3d0-a472-422a-afa6-6bc1e0b79cc5">

**Comment by xplosionmind** [comment]
Pinging @jacksonh: the issue is still happening!
